FROM eternnoir/activiti
MAINTAINER Francesco Bruni <bruni@planetek.it>

ARG branch

WORKDIR /
RUN git clone -b $branch https://teamEreticoTfs:vAsK*AIJFB@tfs.planetek.it/SBU-GS/pkz029_UU_CMEMS/_git/pkz029_UU_CMEMS_WFE /src
