FROM planetek/cmems_activiti:base
MAINTAINER Francesco Bruni <bruni@planetek.it>

ARG branch

WORKDIR /
RUN git clone -b $branch https://teamEreticoTfs:hIEMK-i=d@tfs.planetek.it/SBU-GS/pkz029_UU_CMEMS/_git/pkz029_UU_CMEMS_WFE /src
