FROM planetek/eosai_activiti:base
MAINTAINER Francesco Bruni <bruni@planetek.it>

ARG branch

WORKDIR /
RUN git clone -b $branch https://teamEreticoTfs:hIEMK-i=d@tfs.planetek.it/Planetek%20Hellas/pkh111_EOSAI/_git/pkh111_EOSAI_WFE /src
